package ua.logic.betinvest;

/*
Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class FibSumEven {
    public static void main(String[] args) {
        int x = 0;
        int y = x + 1;
        int z;
        int sum = 0;

        while ((z = x + y) < 4000000) {
            x = y;
            y = z;
            if(z % 2 == 0) {
                sum = sum + z;
            }
        }

        System.out.println(sum);
    }
}
